#include "src/game/envfx_snow.h"

const GeoLayout rex_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, -2, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SHADOW(1, 200, 150),
			GEO_OPEN_NODE(),
				GEO_SCALE(1, 32768),
				GEO_OPEN_NODE(),
					GEO_CULLING_RADIUS(1064),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(1, 0, 80, -53, 19, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, rex_body_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 57, 18, 21, 0, -90, -161),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, rex_Lleg_mesh),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, 62, 126, 12, -19, 0, -90),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, rex_Lshoulder_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, rex_Larm_skinned),
										GEO_ANIMATED_PART(1, 0, 32, 0, rex_Larm_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, 32, 106, -36, -108, -21, -2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, rex_Lwing_mesh),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, -57, 18, 21, 0, -90, -161),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, rex_Rleg_mesh),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, -63, 126, 12, 71, 0, 90),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, rex_Rshoulder_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, rex_Rarm_skinned),
										GEO_ANIMATED_PART(1, 0, 32, 0, rex_Rarm_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(1, -32, 106, -36, -108, 21, 2),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(4, 0, 0, 0, rex_Rwing_mesh),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(1, rex_head_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 196, -12, -19, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, rex_head_mesh),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(1, rex_tail_skinned),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, -123, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, rex_tail_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, rex_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, rex_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
